package com.adadlab.hamza.a9assama.Models;

import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAttribute;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAutoGeneratedKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBTable;

/**
 * Created by DevBlaan on 13/03/2017.
 */
@DynamoDBTable(tableName="House")
public class house {
    private String id;
    private int date;
    private String[] members;

    @DynamoDBHashKey(attributeName = "houseid")
    @DynamoDBAutoGeneratedKey
    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    @DynamoDBAttribute(attributeName="date")
    public int getDate() { return this.date; }
    public void setDate(int date) { this.date = date; }


    @DynamoDBAttribute(attributeName="members")
    public String[] getMembers() { return this.members; }
    public void setMembers( String[] members) { this.members = members; }
}
